In [42]:
# 1. Buatlah Tensor di bawah ini dengan Python:

from numpy import array 
T = array([[[[23, 50],[7,12]], [[75, 21],[57, 12]]], [[[57, 67],[99,43]], [[87, 26],[18, 84]]]])

print(T.shape)

print(T) 

(2, 2, 2, 2)
[[[[23 50]
   [ 7 12]]

  [[75 21]
   [57 12]]]


 [[[57 67]
   [99 43]]

  [[87 26]
   [18 84]]]]


In [43]:
# 2. Lakukan perkalian terhadap matrix berikut:

a = array([[23, 50, 19], [7, 12, 109], [57, 67, 98]])
b = array([[17], [22], [19]])

c = a.dot(c)

print(c)

[[ 9624851 12330249 22311518]
 [16855025 22980287 43356166]
 [23937156 31860450 60384158]]


In [44]:
# 3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

In [45]:
# Transpose

a = array([[23, 50, 19], [7, 12, 109], [57, 67, 98]])

a.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [46]:
# Determinan

from numpy.linalg import det

d = det(a)

print(d)

131344.0000000002


In [47]:
# Invers

from numpy.linalg import inv

i = inv(a) 

print(i)

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
